### 生徒をチームに追加する
POST http://localhost:3000/student/enroll HTTP/1.1
content-type: application/json

{
  "studentId": "1",
  "teamId": "1"
}


### 生徒を休会にしてチームから外す
POST http://localhost:3000/student/leave HTTP/1.1
content-type: application/json

{
  "studentId": "1",
  "teamId": "1"
}
